const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/features/map/components/SpotBottomCard.tsx');
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(
  'import { useEffect, useMemo, useRef, useState } from "react";',
  'import { useEffect, useMemo, useRef, useState } from "react";'
);

content = content.replace(
  '  const [inviteeId, setInviteeId] = useState("");\n  const [inviteMsg, setInviteMsg] = useState<string | null>(null);\n  const fileInputRef = useRef<HTMLInputElement>(null);',
  '  const [collabEnabled, setCollabEnabled] = useState(false);\n  const [friendList, setFriendList] = useState<Array<{ id: string; displayName: string | null; avatarUrl: string | null }>>([]);\n  const [invitedIds, setInvitedIds] = useState<string[]>([]);\n  const [inviteLoadingId, setInviteLoadingId] = useState<string | null>(null);\n  const [inviteMsg, setInviteMsg] = useState<string | null>(null);\n  const fileInputRef = useRef<HTMLInputElement>(null);'
);

content = content.replace(
  '  const displayPrefs = useMemo(() => [...prefs].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [prefs]);',
  '  const displayPrefs = useMemo(() => [...prefs].sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), [prefs]);\n  const canInviteFriendIds = useMemo(() => friendList.map((item) => item.id).filter((id) => id !== userId), [friendList, userId]);'
);

content = content.replace(
  '  useEffect(() => { void loadPrefs(); }, [spot.id, user?.id]);\n  useEffect(() => { setSaveError(null); setSaveSuccess(null); setImages([]); setTags([]); setNote(""); setEmoji(""); setMoodTag(""); setOverall(8); }, [spot.id]);\n  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]);',
  '  useEffect(() => { void loadPrefs(); }, [spot.id, user?.id]);\n  useEffect(() => { setSaveError(null); setSaveSuccess(null); setImages([]); setTags([]); setNote(""); setEmoji(""); setMoodTag(""); setOverall(8); setCollabEnabled(false); setInviteMsg(null); setInvitedIds([]); }, [spot.id]);\n  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]);\n  useEffect(() => {\n    if (!userId) return;\n    let cancelled = false;\n    (async () => {\n      try {\n        const [followsRes, invitesRes] = await Promise.all([\n          fetch(`/api/follows?userId=${encodeURIComponent(userId)}`),\n          fetchInvitesApi(`${INVITES_API}?role=inviter`, { headers: { "x-user-id": userId } }),\n        ]);\n        const followsData = await followsRes.json();\n        const invitesData = await invitesRes.json();\n        if (cancelled) return;\n        setFriendList(followsData.followingProfiles ?? []);\n        const nextInvitedIds = ((invitesData.invites ?? []) as Array<{ spot_id?: string; invitee_id?: string; status?: string }>)\n          .filter((item) => item.spot_id === spot.id && item.status === "pending" && item.invitee_id)\n          .map((item) => String(item.invitee_id));\n        setInvitedIds(Array.from(new Set(nextInvitedIds)));\n      } catch {\n        if (cancelled) return;\n        setFriendList([]);\n        setInvitedIds([]);\n      }\n    })();\n    return () => {\n      cancelled = true;\n    };\n  }, [spot.id, userId]);'
);

content = content.replace(
  '  const handleInvite = async () => {\n    const targetId = inviteeId.trim();\n    if (!targetId) { setInviteMsg("请输入被邀请用户ID"); return; }\n    try {\n      const r = await fetchInvitesApi(`${INVITES_API}`, { method: "POST", headers: { "Content-Type": "application/json", "x-user-id": userId }, body: JSON.stringify({ spotId: spot.id, inviteeId: targetId }) });\n      const d = (await r.json()) as { error?: unknown; duplicated?: boolean };\n      if (!r.ok) { setInviteMsg(d.error ? String(d.error) : "邀请失败"); return; }\n      setInviteMsg(d.duplicated ? "已存在待处理邀请" : "邀请已发送"); if (!d.duplicated) setInviteeId("");\n    } catch { setInviteMsg("邀请失败"); }\n  };',
  '  const handleInvite = async (targetId: string) => {\n    if (!targetId) { setInviteMsg("请选择好友"); return; }\n    setInviteLoadingId(targetId);\n    setInviteMsg(null);\n    try {\n      const r = await fetchInvitesApi(`${INVITES_API}`, { method: "POST", headers: { "Content-Type": "application/json", "x-user-id": userId }, body: JSON.stringify({ spotId: spot.id, inviteeId: targetId }) });\n      const d = (await r.json()) as { error?: unknown; duplicated?: boolean };\n      if (!r.ok) { setInviteMsg(d.error ? String(d.error) : "邀请失败"); return; }\n      setInvitedIds((prev) => prev.includes(targetId) ? prev : [...prev, targetId]);\n      setInviteMsg(d.duplicated ? "存在待处理邀请，已标记为已邀请" : "邀请已发送");\n    } catch {\n      setInviteMsg("邀请失败");\n    } finally {\n      setInviteLoadingId(null);\n    }\n  };'
);

content = content.replace(
  '<section className="rounded-3xl border border-violet-200/70 bg-violet-50/60 p-4 dark:border-violet-900/40 dark:bg-violet-950/20"><p className="text-sm font-medium text-violet-800 dark:text-violet-200">邀请协作记录</p><div className="mt-2 flex gap-2"><input value={inviteeId} onChange={(e) => setInviteeId(e.target.value)} placeholder="输入被邀请 userId" className="flex-1 rounded-xl border border-zinc-200 px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900" /><button type="button" onClick={handleInvite} className="rounded-xl bg-violet-500 px-3 py-2 text-sm text-white">邀请</button></div>{inviteMsg ? <p className="mt-1 text-xs text-zinc-600 dark:text-zinc-300">{inviteMsg}</p> : null}</section>',
  '<section className="rounded-3xl border border-violet-200/70 bg-violet-50/60 p-4 dark:border-violet-900/40 dark:bg-violet-950/20"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-violet-800 dark:text-violet-200">邀请好友共同评价</p><p className="mt-1 text-xs text-violet-700/80 dark:text-violet-200/75">勾选后展示你的好友列表，可逐个发起邀请。</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-full bg-white/80 px-3 py-1.5 text-xs text-violet-700 shadow-sm dark:bg-zinc-900/70 dark:text-violet-100"><input type="checkbox" checked={collabEnabled} onChange={(e) => setCollabEnabled(e.target.checked)} className="h-4 w-4 rounded border-violet-300 text-violet-500 focus:ring-violet-400" /><span>邀请协作</span></label></div>{collabEnabled ? <div className="mt-3 space-y-3">{canInviteFriendIds.length === 0 ? <p className="rounded-2xl border border-dashed border-violet-200 bg-white/70 px-3 py-4 text-sm text-zinc-500 dark:border-violet-900/50 dark:bg-zinc-900/40 dark:text-zinc-300">你还没有可邀请的好友，请先在个人页关注好友。</p> : friendList.filter((item) => item.id !== userId).map((friend) => { const invited = invitedIds.includes(friend.id); const loading = inviteLoadingId === friend.id; return <div key={friend.id} className="flex items-center justify-between gap-3 rounded-2xl bg-white/80 px-3 py-3 shadow-sm dark:bg-zinc-900/60"><div className="flex min-w-0 items-center gap-3">{friend.avatarUrl ? <img src={friend.avatarUrl} alt={friend.displayName ?? friend.id} className="h-10 w-10 rounded-full object-cover" /> : <div className="flex h-10 w-10 items-center justify-center rounded-full bg-violet-100 text-sm font-semibold text-violet-600 dark:bg-violet-900/40 dark:text-violet-200">{(friend.displayName ?? friend.id).slice(0, 1).toUpperCase()}</div>}<div className="min-w-0"><p className="truncate text-sm font-medium text-zinc-900 dark:text-zinc-100">{friend.displayName ?? `${friend.id.slice(0, 6)}…`}</p><p className="text-[11px] text-zinc-500">{friend.id.slice(0, 6)}…</p></div></div><button type="button" disabled={invited || loading} onClick={() => void handleInvite(friend.id)} className={cn("rounded-xl px-3 py-2 text-sm font-medium transition", invited ? "cursor-not-allowed bg-zinc-200 text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400" : "bg-violet-500 text-white hover:bg-violet-400 disabled:opacity-60")}>{loading ? "发送中…" : invited ? "已邀请" : "邀请"}</button></div>; })}</div> : null}{inviteMsg ? <p className="mt-2 text-xs text-zinc-600 dark:text-zinc-300">{inviteMsg}</p> : null}</section>'
);

fs.writeFileSync(filePath, content, 'utf8');
console.log('✅ SpotBottomCard invite area patched successfully');
