import fs from 'fs';
const lines = [
  '"use client";',
  '',
  'import { createContext, useCallback, useContext, useEffect, useState } from "react";',
  'import type { User } from "@supabase/supabase-js";',
  'import { createSupabaseBrowser } from "@/lib/supabase/browser";',
  '',
  'type AuthCtx = {',
  '  user: User | null;',
  '  displayName: string;',
  '  avatarUrl: string | null;',
  '  loading: boolean;',
  '  signOut: () => Promise<void>;',
  '};',
  '',
  'const AuthContext = createContext<AuthCtx>({',
  '  user: null, displayName: "", avatarUrl: null, loading: true, signOut: async () => {},',
  '});',
  '',
  'export function AuthProvider({ children }: { children: React.ReactNode }) {',
  '  const [user, setUser] = useState<User | null>(null);',
  '  const [loading, setLoading] = useState(true);',
  '',
  '  useEffect(() => {',
  '    const sb = createSupabaseBrowser();',
  '    sb.auth.getSession().then((res) => {',
  '      // eslint-disable-next-line @typescript-eslint/no-explicit-any',
  '      setUser((res as any).data?.session?.user ?? null);',
  '      setLoading(false);',
  '    });',
  '    const { data: sub } = sb.auth.onAuthStateChange((_ev, session) => {',
  '      setUser(session?.user ?? null);',
  '    });',
  '    return () => sub.subscription.unsubscribe();',
  '  }, []);',
  '',
  '  const signOut = useCallback(async () => {',
  '    await createSupabaseBrowser().auth.signOut();',
  '  }, []);',
  '',
  '  const meta = user?.user_metadata as { full_name?: string; avatar_url?: string } | undefined;',
  '  const displayName = meta?.full_name ?? (user?.email ? user.email.split("@")[0] : "访客");',
  '  const avatarUrl = meta?.avatar_url ?? null;',
  '',
  '  return (',
  '    <AuthContext.Provider value={{ user, displayName, avatarUrl, loading, signOut }}>',
  '      {children}',
  '    </AuthContext.Provider>',
  '  );',
  '}',
  '',
  'export function useAuth() { return useContext(AuthContext); }',
  '',
].join('\n');
fs.writeFileSync('src/lib/auth/AuthProvider.tsx', lines, 'utf8');
console.log('AuthProvider.tsx ok');
